package com.gft.designsystem

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import com.gft.designsystem.whitelabel.DarkWhiteLabelColorScheme
import com.gft.designsystem.whitelabel.LightWhiteLabelColorScheme

// ideally this file should be autogenerated by Figma script
open class LightAppColorScheme : AppColorScheme, LightWhiteLabelColorScheme() {
    override val color11: Color = Color(0xff11bb33) // <-- overridden color
    override val color21: Color = Color(0xff99ddaa) // <-- new color
}

open class DarkAppColorScheme : AppColorScheme, DarkWhiteLabelColorScheme() {
    override val color11: Color = Color(0xff11bb33) // <-- overridden color
    override val color21: Color = Color(0xff99ddaa) // <-- new color
}

// ad-hoc reassigning examples
fun reassignSingleValue(): AppColorScheme {
    return object : LightAppColorScheme() {
        override val color11: Color = Color.Red
    }
}

@Composable
fun reassignSingleValueInCurrentTheme(): AppColorScheme {
    return object : AppColorScheme by AppDesignSystem.colors {
        override val color11: Color = Color.Red
    }
}
