package com.gft.designsystem

import androidx.compose.ui.graphics.Color
import com.gft.designsystem.whitelabel.LightWhiteLabelColorScheme
import com.gft.designsystem.whitelabel.WhiteLabelColorScheme

// ideally this file should be autogenerated by Figma script
class LightAppColorScheme : AppColorScheme, WhiteLabelColorScheme by LightWhiteLabelColorScheme() {
    override val color11: Color = Color(0xff11bb33) // <-- overridden color
    override val color21: Color = Color(0xff99ddaa) // <-- new color
}
