package com.gft.mobius.components.styles

import androidx.compose.ui.text.TextStyle
import com.gft.designsystem.Token

open class DefaultMobiusStyles : MobiusStyles {
    override val screenStyle: ScreenStyle = DefaultScreenStyle()
    override val dialogScreenStyle: DialogScreenStyle = DefaultDialogScreenStyle()
    override val contentStyle: ContentStyle = DefaultContentStyle()
    override val scrollableContentStyle: ContentStyle = DefaultContentStyle()
    override val dialogContentStyle: ContentStyle = DefaultDialogContentStyle()
    override val dialogScrollableContentStyle: ContentStyle = DefaultDialogContentStyle()
    override val contentElementSpacerStyle: ContentElementSpacerStyle = DefaultContentElementSpacerStyle()
    override val groupStyle: GroupStyle = DefaultGroupStyle()
    override val groupElementSpacerStyle: GroupElementSpacerStyle = DefaultGroupElementSpacerStyle()
    override val cardStyle: CardStyle = DefaultCardStyle()
    override val outlinedCardStyle: CardStyle = OutlinedCardStyle()
    override val elevatedCardStyle: CardStyle = ElevatedCardStyle()
    override val buttonStyle: ButtonStyle = DefaultButtonStyle()
    override val outlinedButtonStyle: ButtonStyle = OutlinedButtonStyle()
    override val elevatedButtonStyle: ButtonStyle = ElevatedButtonStyle()
    override val filledTonalButtonStyle: ButtonStyle = FilledTonalButtonStyle()
    override val textButtonStyle: ButtonStyle = TextButtonStyle()
    override val radioButtonStyle: RadioButtonStyle = DefaultRadioButtonStyle()
    override val iconSizeStyle: IconSizeStyle = DefaultIconSizeStyle()
    override val tab: TabStyle = DefaultTabStyle()
    override val primaryTabRow: TabRowStyle = PrimaryTabRowStyle()
    override val secondaryTabRow: TabRowStyle = SecondaryTabRowStyle()
    override val primaryScrollableTabRow: ScrollableTabRowStyle = PrimaryScrollableTabRowStyle()
    override val secondaryScrollableTabRow: ScrollableTabRowStyle = SecondaryScrollableTabRowStyle()
    override val text: Token<TextStyle> = DefaultTextStyle
    override val textField: TextFieldStyle = DefaultTextFieldStyle()
    override val outlinedTextField: TextFieldStyle = DefaultOutlinedTextFieldStyle()
    override val horizontalDivider: HorizontalDividerStyle = DefaultHorizontalDividerStyle()
    override val switchStyle: SwitchStyle = DefaultSwitchStyle()
    override val checkboxStyle: CheckboxStyle = DefaultCheckboxStyle()
    override val timePickerStyle: TimePickerStyle = DefaultTimePickerStyle()
    override val timeInputStyle: TimeInputStyle = DefaultTimeInputStyle()
    override val datePickerStyle: DatePickerStyle = DefaultDatePickerStyle()
    override val tooltipStyle: TooltipStyle = DefaultTooltipStyle()
    override val infoBoxStyle: InfoBoxStyle = DefaultInfoBoxStyle()
    override val infoBoxPositionProviderStyle: InfoBoxPositionProviderStyle = DefaultInfoBoxPositionProviderStyle()
    override val sliderThumbStyle: SliderThumbStyle = DefaultSliderThumbStyle()
    override val sliderTooltipStyle: TooltipStyle = SliderTooltipStyle()
    override val sliderTrackStyle: SliderTrackStyle = DefaultSliderTrackStyle()
}
