package com.gft.designsystem.whitelabel

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

// ideally this file should be autogenerated by Figma script
class LightWhiteLabelColorScheme : WhiteLabelColorScheme {
    override val color11: Color = Color(0xff222222)
    override val color12: Color = Color(0xff444444)
    override val color13: Color = Color(0xff666666)
    override val color14: Color = Color(0xff888888)
    override val color15: Color = Color(0xffaaaaaa)
    override val color16: Color = Color(0xffcccccc)
    override val color17: Color = Color(0xffeeeeee)
}

// or....
val darkWhiteLabelColorScheme : WhiteLabelColorScheme = object : WhiteLabelColorScheme {
    override val color11: Color = Color(0xff222222)
    override val color12: Color = Color(0xff444444)
    override val color13: Color = Color(0xff666666)
    override val color14: Color = Color(0xff888888)
    override val color15: Color = Color(0xffaaaaaa)
    override val color16: Color = Color(0xffcccccc)
    override val color17: Color = Color(0xffeeeeee)
}

// reassigning examples
fun reassignSingleValue(): WhiteLabelColorScheme {
    return object : WhiteLabelColorScheme by LightWhiteLabelColorScheme() {
        override val color11: Color = Color.Red
    }
}

@Composable
fun reassignSingleValueInCurrentTheme(): WhiteLabelColorScheme {
    return object : WhiteLabelColorScheme by LocalWhiteLabelSystem.current.colors {
        override val color11: Color = Color.Red
    }
}
